---

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: "*"

message: In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.
